# Generated by Django 4.1.3 on 2022-11-02 20:14

import administrationApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('account_number', models.CharField(default=administrationApp.models.customer_account_no_generator, max_length=100, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('Savings Account', 'Savings Account'), ('Checking Account', 'Checking Account')], default='Savings Account', help_text='Choose right type of the account', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_balance', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Accounts',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Enter customer display name', max_length=100)),
                ('customer_role', models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], default='Primary', help_text='Choose Right Customer Role', max_length=100, null=True)),
                ('phone_number', models.CharField(help_text='Enter Phone number with country code, Ex: +1-111-222-3333', max_length=100)),
                ('user_profile', models.OneToOneField(help_text='Choose customer online profile', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customers',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='mn_accounts_customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrationApp.account')),
                ('customer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrationApp.customer')),
            ],
            options={
                'verbose_name': 'Accounts Customers',
                'verbose_name_plural': 'Accounts Customers',
                'unique_together': {('account_number', 'customer_info')},
            },
        ),
    ]
