# Generated by Django 4.1.3 on 2022-11-02 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrationApp', '0002_debit_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='debit_card_usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_amount', models.FloatField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.CharField(blank=True, help_text='Where this money has been spent?', max_length=100, null=True)),
                ('status_of_spent', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Current status of transaction', max_length=100)),
                ('debit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrationApp.debit_cards')),
            ],
            options={
                'verbose_name': 'Debit Card Usage',
                'verbose_name_plural': 'Debit Card Usage',
            },
        ),
    ]
