# Generated by Django 4.1.3 on 2022-11-02 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrationApp', '0003_debit_card_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(max_length=100)),
                ('employee_title', models.CharField(max_length=100)),
                ('employee_designation', models.CharField(max_length=100)),
                ('employee_start_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('office_contact_number', models.CharField(help_text='Enter Phone number with country code, Ex: +1-111-222-3333', max_length=100)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
