# Generated by Django 4.1.3 on 2022-11-02 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrationApp', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter bank name', max_length=100)),
                ('legal_name', models.CharField(max_length=100)),
                ('established_date', models.DateField()),
                ('customer_care_number', models.CharField(help_text='Enter Phone number with country code, Ex: +1-111-222-3333', max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Bank',
            },
        ),
        migrations.CreateModel(
            name='bank_branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=25)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrationApp.bank')),
            ],
            options={
                'verbose_name': 'Bank Branch',
                'verbose_name_plural': 'Bank Branch',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrationApp.bank_branch'),
            preserve_default=False,
        ),
    ]
