# Generated by Django 4.1.3 on 2022-11-03 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrationApp', '0006_department_alter_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanId', models.CharField(help_text='Loan application number', max_length=100, unique=True)),
                ('loan_type', models.CharField(choices=[('Personal Loan', 'Personal Loan'), ('Auto Loan', 'Auto Loan'), ('Mortgage Loan', 'Mortgage Loan'), ('Education Loan', 'Education Loan')], max_length=100)),
                ('requesting_amount', models.FloatField()),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('status_changed_date', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
            },
        ),
        migrations.CreateModel(
            name='loan_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('DueTime', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrationApp.loan')),
            ],
            options={
                'verbose_name': 'Loan Payments',
                'verbose_name_plural': 'Loan Payments',
            },
        ),
    ]
