# Generated by Django 4.1.3 on 2022-11-03 18:31

import administrationApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrationApp', '0008_address_card_info_credit_cards_loan_supporting_docs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='branch_code',
            new_name='department_code',
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrationApp.bank_branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debit_cards',
            name='card_num',
            field=models.CharField(default=administrationApp.models.card_number_generator, help_text='Debit Card number', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeId',
            field=models.CharField(default=administrationApp.models.employee_id_generator, max_length=100),
        ),
    ]
