# Generated by Django 4.1.3 on 2022-11-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrationApp', '0009_rename_branch_code_department_department_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrationApp.address'),
        ),
        migrations.AddField(
            model_name='bank_branch',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrationApp.address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrationApp.address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrationApp.address'),
        ),
    ]
