# Generated by Django 4.1.3 on 2022-11-24 06:26

import administrationApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrationApp', '0010_bank_address_bank_branch_address_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loanId',
            field=models.CharField(default=administrationApp.models.loan_number_generator, help_text='Loan application number', max_length=100, unique=True),
        ),
    ]
